# Imports

In [3]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from nltk.stem import WordNetLemmatizer
import nltk
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
nltk.download('wordnet')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /home/allan/nltk_data...
[nltk_data] Downloading package punkt to /home/allan/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

# Load Data

In [4]:
df = pd.read_csv("../data.csv")
df.head()

   doc_id  ... sentiment
0       1  ...  Negative
1       2  ...  Positive
2       3  ...  Negative
3       4  ...  Positive
4       5  ...  Negative

[5 rows x 5 columns]

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   doc_id      650 non-null    int64
 1   text        650 non-null    str
 2   category_1  650 non-null    int64
 3   category_2  553 non-null    str
 4   sentiment   639 non-null    str
dtypes: int64(2), str(3)
memory usage: 25.5 KB

In [6]:
df[df["category_2"].isnull()]

     doc_id  ... sentiment
50       51  ...  Positive
51       52  ...  Negative
52       53  ...   Neutral
53       54  ...  Positive
54       55  ...  Negative
..      ...  ...       ...
590     591  ...  Positive
591     592  ...  Negative
592     593  ...   Neutral
593     594  ...  Positive
594     595  ...   Neutral

[97 rows x 5 columns]

In [7]:
df[df["sentiment"].isnull()]

     doc_id  ... sentiment
100     101  ...       NaN
101     102  ...       NaN
102     103  ...       NaN
103     104  ...       NaN
104     105  ...       NaN
105     106  ...       NaN
106     107  ...       NaN
107     108  ...       NaN
108     109  ...       NaN
109     110  ...       NaN
395     396  ...       NaN

[11 rows x 5 columns]

In [8]:
df["category_1"].value_counts(dropna=False)

category_1
 1    169
 2    140
 3    129
 4    117
 5     85
-1     10
Name: count, dtype: int64

In [9]:
df["category_1"].value_counts(normalize=True, dropna=False)

category_1
 1    0.260000
 2    0.215385
 3    0.198462
 4    0.180000
 5    0.130769
-1    0.015385
Name: proportion, dtype: float64